let texto = document.getElementById("texto")
let pass = document.getElementById("pass")
let textarea = document.getElementById("textArea")
let label = document.getElementById("label")
let img = document.getElementById("img")
let checkbox = document.getElementById("check")
let radio = document.getElementById("radio")
let boton = document.getElementById("boton")